name: previsao_tempo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/temp_min.png
    - assets/temp_max.png
    - assets/chuvoso.png
    - assets/ensolarado.png
    - assets/nublado.png
    - assets/pancadas_chuva.png
    - assets/parc_nublado.png
    - assets/uv_indice.png
    - assets/not_find.png